[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = { version = "0.3.0", features = ["serde"] }
num = "0.4.1"
polygonical = "0.5.0"
regex = "1.10.2"
